export const sampleMentors = [
  {
    name: "Ayşe Yılmaz",
    image: "https://thispersondoesnotexist.com",
    title: "Yazılım Mühendisi",
    talents: ["C#", "DevOps", "Software Engineer"],
  },
  {
    name: "Mehmet Demir",
    image: "https://thispersondoesnotexist.com",
    title: "Frontend Developer",
    talents: ["JavaScript", "React", "Interview Preparation"],
  },
  {
    name: "Zeynep Karaca",
    image: "https://thispersondoesnotexist.com",
    title: "Çözüm Mühendisi",
    talents: ["Solutions Engineering", "Sales Engineering", "DevOps"],
  },
  {
    name: "Ahmet Koç",
    image: "https://thispersondoesnotexist.com",
    title: "Full Stack Developer",
    talents: ["JavaScript", "C#", "React"],
  },
  {
    name: "Elif Şahin",
    image: "https://thispersondoesnotexist.com",
    title: "Veri Analisti",
    talents: ["Interview Preparation", "Solutions Engineering", "DevOps"],
  },
  {
    name: "Kerem Uçar",
    image: "https://thispersondoesnotexist.com",
    title: "Backend Developer",
    talents: ["C#", "Software Engineer", "DevOps"],
  },
  {
    name: "Deniz Aksoy",
    image: "https://thispersondoesnotexist.com",
    title: "Frontend Engineer",
    talents: ["React", "Typescript", "JavaScript"],
  },
  {
    name: "Hale Güler",
    image: "https://thispersondoesnotexist.com",
    title: "Satış Mühendisi",
    talents: ["Sales Engineering", "Solutions Engineering", "C#"],
  },
  {
    name: "Burak Aydın",
    image: "https://thispersondoesnotexist.com",
    title: "DevOps Uzmanı",
    talents: ["DevOps", "C#", "Interview Preparation"],
  },
  {
    name: "Melis Ergin",
    image: "https://thispersondoesnotexist.com",
    title: "Çözüm Danışmanı",
    talents: ["Solutions Engineering", "Sales Engineering", "React"],
  },
  {
    name: "Emre Tunalı",
    image: "https://thispersondoesnotexist.com",
    title: "Software Engineer",
    talents: ["C#", "DevOps", "JavaScript"],
  },
  {
    name: "Gizem Bayraktar",
    image: "https://thispersondoesnotexist.com",
    title: "Product Manager",
    talents: ["Interview Preparation", "Sales Engineering", "React"],
  },
  {
    name: "Onur Arslan",
    image: "https://thispersondoesnotexist.com",
    title: "Full Stack Developer",
    talents: ["JavaScript", "Typescript", "C#"],
  },
  {
    name: "Buse Kara",
    image: "https://thispersondoesnotexist.com",
    title: "UI/UX Designer",
    talents: ["React", "Interview Preparation", "Sales Engineering"],
  },
  {
    name: "Ozan Yüce",
    image: "https://thispersondoesnotexist.com",
    title: "Software Architect",
    talents: ["C#", "DevOps", "Solutions Engineering"],
  },
  {
    name: "Merve Sezer",
    image: "https://thispersondoesnotexist.com",
    title: "React Developer",
    talents: ["JavaScript", "React", "Interview Preparation"],
  },
  {
    name: "Tuna Korkmaz",
    image: "https://thispersondoesnotexist.com",
    title: "DevOps Mühendisi",
    talents: ["DevOps", "C#", "Typescript"],
  },
  {
    name: "İpek Gür",
    image: "https://thispersondoesnotexist.com",
    title: "Çözüm Mühendisi",
    talents: ["Solutions Engineering", "Sales Engineering", "JavaScript"],
  },
  {
    name: "Baran Çelik",
    image: "https://thispersondoesnotexist.com",
    title: "Backend Developer",
    talents: ["C#", "Software Engineer", "DevOps"],
  },
  {
    name: "Selin Akar",
    image: "https://thispersondoesnotexist.com",
    title: "Mentor & Danışman",
    talents: ["Interview Preparation", "Solutions Engineering", "React"],
  },
];
